services:
  - type: web
    name: Expense Tracker
    env: python
    repo: https://github.com/SyamGopalGuttula/personal_finance_tracker
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --clear
      python manage.py migrate
    startCommand: gunicorn finance_tracker.wsgi:application --preload --workers 3 --bind 0.0.0.0:8000
    envVars:
      - key: SECRET_KEY
        value: "your-very-secret-key"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "personal-finance-tracker-x3kl.onrender.com,localhost,127.0.0.1"
